### ISSUE TITLE
Allow autoloading of DrumkitContext step functions in parent project's Behat setup

### ISSUE THREAD

**Issue by sensespidey** [consensus-enterprises/drumkit#3]
To make it easy to include Drumkit's Behat features functions in a parent project's behat.yml as:

```
default:
  suites:
    default:
      contexts:
        - DrumkitContext
```
The project needs to be able to autoload a namespaced FeatureContext class, specified in the composer.json with a paragraph like:

```
  "autoload-dev": {
    "psr-4": {
      "Drumkit\\": ".mk/features/bootstrap"
    }
  },
```
This negates the need to ad-hoc `require()` the Drumkit classes, and enables `behat -dl` to show the Drumkit step functions along with others available to the project.
